name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: elgohr/Publish-Docker-Github-Action@master
    - name: Build the Docker image
      with:
        name: rodrigodealer/secrets-injector
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
