apiVersion: v1
kind: Secret
metadata:
  name: secrets-injector-config
type: Opaque
stringData:
  config.yaml: |-
    config:
    provider:
        name: vault
        token: s.7LXjNtEutLhDwmW8Ff0VuTRt
        address: "http://vault:8200"
    environment:
      - ONE_ENV=hello_set
      - TWO_ENV=hello_set
